# Configuração do banco de dados Oracle
spring.datasource.url=jdbc:oracle:thin:@//200.95.188.251:1521/ORACLE
spring.datasource.username=trans
spring.datasource.password=trans
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect

# Configuração JWT
jwt.secret=Trans@1905
jwt.expiration=3600000
jwt.issuer=apiTransfuturo

# Configuração Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
