# Configuração do servidor
server.port=8081

# Configuração de logger
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.com.transfuturo=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Configuração do banco de dados Oracle
spring.datasource.url=jdbc:oracle:thin:@//200.95.188.251:1521/ORACLE
spring.datasource.username=trans
spring.datasource.password=trans
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Configuração JWT - mensagem-teste + Trans@1905
jwt.secret=g1GqzH9mJvYwXkUu3xK3Zrj7YzQkzKZzv+KZVZxYk6g=
jwt.expiration=3600000
jwt.issuer=apiTransfuturo

# Configuração Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
